route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "web.hook"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: https://webhook.site/1f88d6d1-fd3a-49b2-b4d9-7f0defd22796
